name: Build

on:
  push:
    paths-ignore:
      - '*.md'
      - '*LICENSE'
  pull_request:

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

jobs:
  build-windows:
    name: Build Windows (${{matrix.name}})
    runs-on: ${{matrix.runner}}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MSVC x86_64
            runner: windows-latest
            preset: msvc
            msvc_arch: amd64
            vcpkg_arch: x64
            artifact_arch: x86_64
          # - name: MSVC arm64
          #   runner: windows-11-arm
          #   preset: arm64-msvc
          #   msvc_arch: arm64
          #   vcpkg_arch: arm64
          #   artifact_arch: arm64
          # - name: Clang x86_64
          #   runner: windows-latest
          #   preset: clang
          #   msvc_arch: amd64
          #   vcpkg_arch: x64
          #   artifact_arch: x86_64

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Enable Visual Studio environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.msvc_arch}}

      # msvc-dev-cmd sets VCPKG_ROOT, set it back
      - name: Override VCPKG_ROOT
        run: echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Install dependencies
        run: |
          choco install ninja
          vcpkg install freetype:${{matrix.vcpkg_arch}}-windows-static zstd:${{matrix.vcpkg_arch}}-windows-static

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: latest
          cache: true

      - name: Configure CMake
        run: cmake --preset x-windows-ci-${{matrix.preset}}

      - name: Build
        run: cmake --build --preset x-windows-ci-${{matrix.preset}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dusk-${{env.DUSK_VERSION}}-win32-msvc-${{matrix.artifact_arch}}
          path: |
            build/install/*.exe
            build/install/*.dll
            build/install/res/
            build/install/debug.7z
